use PracticeDB;

create table Employee 
(EmpID Int, FullName VARCHAR(50), Salary INT, DeptID INT, City VARCHAR(30));

create table Department (DeptID INT, DeptName VARCHAR(50));

insert into Employee values (1001, 'Rahul', 60000, 1, 'Pune'),
(1002, 'Rahul', 60000, 1, 'Pune'),
(1003, 'Rahul', 60000, 1, 'Pune'),
(1004, 'Pooja', 50000, 2, 'Uttar Pradesh'),
(1005, 'Sneha', 90000, 2, 'Surat'),
(1006, 'Mohit', 120000, 1, 'Mumbai'),
(1007, 'Ashok', 110000, 3, 'Delhi'),
(1008, 'Karan', 90000, 3, 'Mumbai'),
(1009, 'Sam',	105000,	1, 'Telengana');

select * from Employee;

-- 10. Using a Subquery, write a query to find the 3rd highest salary from the Employee table. (Do not use TOP).
select max(salary) as '3rd highest salary' from Employee where Salary < (select max(salary) from Employee where Salary < (select MAX(Salary) from Employee));

-- 11. Write a query using an INNER JOIN to fetch the FullName and DeptName of all employees whose salary is greater than 50,000.
select e.fullName, d.DeptName from Employee e inner join Department d on e.DeptID = d.DeptID where e.Salary > 50000;

-- 12. Write a query to find duplicate DeptID entries in the Employee table, displaying only those DeptIDs where the count of employees is greater than 5.
select DeptID, count(*) as EmployeeCount from Employee group by DeptID having count(*) > 5;

-- 13. Create a Temporary Table named #TempEmp with two columns (ID, Name). Insert two dummy records into it.
select * into #TempEmp from (select 1 as ID, 'Dummy1' as Name union all select 2, 'Dummy2') as TempData;

create table Orders 
(OrderID INT PRIMARY KEY, CustomerID INT, OrderDate DATE, TotalAmount FLOAT);

-- 14. Read the above Case Study and answer the following:
-- (a) Write a query to calculate the total sales (Sum of TotalAmount) generated by each CustomerID.
select CustomerID, sum(TotalAmount) as TotalSales from Orders group by CustomerID;

-- (b) Extend the query from part (a) to only show customers whose total aggregate sales exceed 100,000.
select CustomerID, sum(TotalAmount) as TotalSales from Orders group by CustomerID having TotalAmount > 100000;

-- (c) Write the SQL syntax to create a User Defined Function (UDF) named GetDiscount. It should accept an Amount (FLOAT) as an input parameter and return a 10% discount value.
GO
create function GetDiscount (@Amount FLOAT) returns FLOAT as begin return @Amount * 0.10 end;